### ISSUE TITLE
Failed to start input device

### ISSUE THREAD

**Issue by MrSorcus** [JFreegman/toxic#435]
Sometimes crashed audio call...

Toxic (Linux) <- audio call -> uTox (Ubuntu) - work
Toxic (Linux) <- audio call -> qTox (Windows 7) - work
Toxic (Linux) <- audio call -> uTox 0.12.2 (Windows 10) - don't work
Toxic (Linux) <- audio call -> qTox (Window 10) - work
Toxic (Linux) <- audio call -> qTox (Windows 8) - don't work

Log:
```
Call started! Type: "/hangup" to end it.
Failed to start input device
Failed to register input handler!
```
qTox. Windows 8.
```
Qt: 5.5.1
v1.8.1
toxcore: 0.1.5
Win 8.1 Pro x64
```
Toxic on Archlinux
```
Toxic version 0.7.2_r1747
Toxcore version 0.1.5
Qt 5.8.0-5
```

**Comment by JFreegman** [comment]
What happens when the clients that don't work try to initiate the call?

**Comment by MrSorcus** [comment]
@JFreegman 
I don't have any output in logs (Toxic). Only this error.
```
Failed to start input device
Failed to register input handler!
```
But i can't reproduce it with other person with similar configuration (Windows 8.1 with last updates and last qtox/utox portable)...

**Comment by JFreegman** [comment]
Pretty mysterious. Maybe @mannol can help since he's the A/V guy?

**Comment by mannol** [comment]
@JFreegman no idea what's wrong here.

**Comment by GrayHatter** [comment]
if it's a single client, my best guess is a bit rate issue.

debug info from uTox would be really helpful in tracking this down

That said, it's odd that the issue is a input device issue...

**Comment by JFreegman** [comment]
>it's odd that the issue is a input device issue...

Exactly. Why would your own input device fail because of the other person's client. I'll have to look a bit deeper into this when I have the time.

**Comment by GrayHatter** [comment]
My first thought, does toxic accept toxav bitrate suggestion?

@mannol Does toxav change it's default bitrate on a packet from the peer?

**Comment by mannol** [comment]
@GrayHatter toxic doesn't do auto bitrate.

**Comment by MrSorcus** [comment]
Toxic -- Call --> uTox
Result: I don't listen him (uTox client). But he listen me.
https://gist.github.com/MrSorcus/6013ee154a656fe8521df857445fd3e5
Version uTox: Alpha 0.9.7

**Comment by MrSorcus** [comment]
GDB log file.
```
laptop% cat ~/trace.log
Continuing.
[New Thread 0x7fea4419d700 (LWP 32351)]
[New Thread 0x7fea3f7fe700 (LWP 32352)]
[New Thread 0x7fea3e7e5700 (LWP 32353)]

Thread 1 "toxic" received signal SIGINT, Interrupt.
0x00007fea4f828ffd in nanosleep () from /usr/lib/libc.so.6

Thread 9 (Thread 0x7fea3e7e5700 (LWP 32353)):
#0  0x00007fea4f85048d in poll () at /usr/lib/libc.so.6
#1  0x00007fea4fd8f7a6 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fea4fd8fb32 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007fea50375446 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007fea4fdb7175 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007fea51271454 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fea4f8597df in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7fea3f7fe700 (LWP 32352)):
#0  0x00007fea4f85048d in poll () at /usr/lib/libc.so.6
#1  0x00007fea4fd8f7a6 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fea4fd8f8bc in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fea4fd8f901 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007fea4fdb7175 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007fea51271454 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fea4f8597df in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7fea4419d700 (LWP 32351)):
#0  0x00007fea4f85048d in poll () at /usr/lib/libc.so.6
#1  0x00007fea44c2565e in  () at /usr/lib/libasound.so.2
#2  0x00007fea44c2592b in snd_pcm_wait () at /usr/lib/libasound.so.2
#3  0x00007fea50ac5b41 in  () at /usr/lib/libopenal.so.1
#4  0x00007fea50ad06c7 in  () at /usr/lib/libopenal.so.1
#5  0x00007fea51271454 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fea4f8597df in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fea3ffff700 (LWP 32184)):
#0  0x00007fea4f828ffd in nanosleep () at /usr/lib/libc.so.6
#1  0x00007fea4f852874 in usleep () at /usr/lib/libc.so.6
#2  0x0000000000423141 in do_playing (_p=0x0) at /home/sorcus/aur_builder/v3/pkgbuild/toxic/src/toxic/src/notify.c:294
        has_looping = false
        test_active_notify = false
        i = 50
#3  0x00007fea51271454 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007fea4f8597df in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fea44bcf700 (LWP 32183)):
#0  0x00007fea4f828ffd in nanosleep () at /usr/lib/libc.so.6
#1  0x00007fea4f852874 in usleep () at /usr/lib/libc.so.6
#2  0x000000000042b6e0 in thread_av (data=0x116d2a0) at /home/sorcus/aur_builder/v3/pkgbuild/toxic/src/toxic/src/toxic.c:818
        av = 0x116d2a0
#3  0x00007fea51271454 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007fea4f8597df in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fea47742700 (LWP 32182)):
#0  0x00007fea4f828ffd in nanosleep () at /usr/lib/libc.so.6
#1  0x00007fea4f852874 in usleep () at /usr/lib/libc.so.6
#2  0x000000000043385f in thread_poll (arg=0x0) at /home/sorcus/aur_builder/v3/pkgbuild/toxic/src/toxic/src/audio_device.c:440
        paused = true
        i = 0
        sample = 0
#3  0x00007fea51271454 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007fea4f8597df in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fea48523700 (LWP 32178)):
#0  0x00007fea4f828ffd in nanosleep () at /usr/lib/libc.so.6
#1  0x00007fea4f852874 in usleep () at /usr/lib/libc.so.6
#2  0x000000000042b67f in thread_cqueue (data=0x101a130) at /home/sorcus/aur_builder/v3/pkgbuild/toxic/src/toxic/src/toxic.c:804
        i = 32
        m = 0x101a130
#3  0x00007fea51271454 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007fea4f8597df in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fea48d24700 (LWP 32177)):
#0  0x00007fea4f85048d in poll () at /usr/lib/libc.so.6
#1  0x00007fea52befd22 in _nc_timed_wait () at /usr/lib/libncursesw.so.6
#2  0x00007fea52bca71c in _nc_wgetch () at /usr/lib/libncursesw.so.6
#3  0x00007fea52be24f6 in wget_wch () at /usr/lib/libncursesw.so.6
#4  0x000000000042f4d8 in draw_active_window (m=0x101a130) at /home/sorcus/aur_builder/v3/pkgbuild/toxic/src/toxic/src/windows.c:530
        a = 0x64b7e0 <windows+704>
        ch = 0
        ltr = false
        status = -1
#5  0x000000000042b579 in thread_winref (data=0x101a130) at /home/sorcus/aur_builder/v3/pkgbuild/toxic/src/toxic/src/toxic.c:767
        m = 0x101a130
        draw_count = 9 '\t'
#6  0x00007fea51271454 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007fea4f8597df in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7fea53684c40 (LWP 32137)):
#0  0x00007fea4f828ffd in nanosleep () at /usr/lib/libc.so.6
#1  0x00007fea4f852874 in usleep () at /usr/lib/libc.so.6
#2  0x000000000042c8c6 in main (argc=2, argv=0x7fffa1b15698) at /home/sorcus/aur_builder/v3/pkgbuild/toxic/src/toxic/src/toxic.c:1255
        cur_time = 1488534470
        datafile_exists = true
        p = 0x0
        curl_init = 0
        nameserver_ret = 0
        m = 0x101a130
        nodeslist_ret = 0
        avatarstr = "/avatar \"\"\000\000\000\000\000\000`XiS\352\177\000\000 MiS\352\177\000\000\260Q\261\241\377\177\000\000\000\000\000\000\000\000\000\000\001", '\000' <repeats 15 times>, "\330Q\261\241\377\177\000\000\341\215JS\352\177\000\000\026", '\000' <repeats 15 times>, "\001", '\000' <repeats 15 times>, "\001\000\000\000\000\000\000\000\310IiS\352\177\000\000\302[\362\001\000\000\000\000\070 xO\352\177\000\000\000\000\000\000\000\000\000\000 MiS\352\177\000\000 Q\261\241\377\177\000\000\340Q\261\241\001\000\000\000\310IiS\352\177\000\000\020Q\261\241\377\177\000\000\001\322\005P\352\177\000\000"...
        last_save = 1488534346
Continuing.
```

**Comment by MrSorcus** [comment]
Any ideas?
How can i improve gdb output?

**Comment by MrSorcus** [comment]
Today i'm testing audio call from qtox. And...It's work. But not in toxic. In toxic audio call always failed...

**Comment by GrayHatter** [comment]
qTox and Antox are problematic when testing. The only clients that are reliable when it comes to AV are, uTox and toxic. 

Echo bot also works very well.

**Comment by MrSorcus** [comment]
It still not working sometimes. Failed randomly.
With any version, any clients, any OS.

**Comment by JFreegman** [comment]
Closing due to inactivity
