### ISSUE TITLE
Bus error while destroying pthread mutex.

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#505]
```
mazocomp$ egdb toxic toxic.core
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-openbsd6.3".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from toxic...done.
[New process 238304]
[New process 218364]
[New process 108033]
[New process 239431]
[New process 271046]
[New process 262108]
[New process 414548]
Core was generated by `toxic'.
Program terminated with signal SIGBUS, Bus error.
#0  _libc_pthread_mutex_destroy (mutexp=0x1355f18a6958) at /usr/src/lib/libc/thread/rthread_mutex.c:82
82                      if (mutex->lock != UNLOCKED) {
[Current thread is 1 (process 238304)]
(gdb) bt
#0  _libc_pthread_mutex_destroy (mutexp=0x1355f18a6958) at /usr/src/lib/libc/thread/rthread_mutex.c:82
#1  0x000013530e42075f in set_call (call=<optimized out>, start=false) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/audio_call.c:82
#2  stop_transmission (call=<optimized out>, friend_number=<optimized out>) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/audio_call.c:244
#3  0x000013530e4218a3 in stop_current_call (self=0x13530e641b48 <windows+2520>) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/audio_call.c:895
#4  0x000013530e40362e in kill_chat_window (self=0x13530e641b48 <windows+2520>, m=0x1355bca46400) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/chat.c:144
#5  0x000013530e40480d in chat_onKey (self=0x13530e641b48 <windows+2520>, m=0x1355bca46400, key=<optimized out>, ltr=<optimized out>) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/chat.c:987
#6  0x000013530e41fd65 in draw_active_window (m=0x1355bca46400) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/windows.c:568
#7  0x000013530e41b428 in thread_winref (data=0x1355bca46400) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/toxic.c:824
#8  0x00001355cc72107e in _rthread_start (v=0x16) at /usr/src/lib/librthread/rthread.c:96
#9  0x0000135542fc3fbb in __tfork_thread () at /usr/src/lib/libc/arch/amd64/sys/tfork_thread.S:75
#10 0x0000000000000000 in ?? ()
(gdb) bt full
#0  _libc_pthread_mutex_destroy (mutexp=0x1355f18a6958) at /usr/src/lib/libc/thread/rthread_mutex.c:82
        mutex = 0xdfdfdfdfdfdfdfdf
#1  0x000013530e42075f in set_call (call=<optimized out>, start=false) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/audio_call.c:82
No locals.
#2  stop_transmission (call=<optimized out>, friend_number=<optimized out>) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/audio_call.c:244
        error = TOXAV_ERR_CALL_CONTROL_OK
#3  0x000013530e4218a3 in stop_current_call (self=0x13530e641b48 <windows+2520>) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/audio_call.c:895
No locals.
#4  0x000013530e40362e in kill_chat_window (self=0x13530e641b48 <windows+2520>, m=0x1355bca46400) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/chat.c:144
        ctx = 0x13557196e000
        statusbar = 0x13558c2e1800
#5  0x000013530e40480d in chat_onKey (self=0x13530e641b48 <windows+2520>, m=0x1355bca46400, key=<optimized out>, ltr=<optimized out>) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/chat.c:987
        line = "/close", '\000' <repeats 1365 times>
        status_cmd_list = {"online\000", "away\000\000\000", "busy\000\000\000"}
        ctx = 0x13557196e000
        statusbar = <optimized out>
        y = 25
        x = 6
        y2 = 26
        x2 = <optimized out>
#6  0x000013530e41fd65 in draw_active_window (m=0x1355bca46400) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/windows.c:568
        a = 0x13530e641b48 <windows+2520>
        ch = 0
        status = <optimized out>
#7  0x000013530e41b428 in thread_winref (data=0x1355bca46400) at /usr/local/pobj/toxic-0.8.2-no_x11/toxic-0.8.2/src/toxic.c:824
        m = 0x1355bca46400
        draw_count = 5 '\005'
#8  0x00001355cc72107e in _rthread_start (v=0x16) at /usr/src/lib/librthread/rthread.c:96
        thread = 0x16
        retval = <optimized out>
#9  0x0000135542fc3fbb in __tfork_thread () at /usr/src/lib/libc/arch/amd64/sys/tfork_thread.S:75
No locals.
#10 0x0000000000000000 in ?? ()
No symbol table info available.
(gdb)
```

**Comment by JFreegman** [comment]
Can you give me more details as to when this happens and how it can be reproduced?

**Comment by ghost** [comment]
@JFreegman that happened when I ran "/close" inside groupchat window.

**Comment by JFreegman** [comment]
@mazocomp Does it still happen on the latest version? Every time? If so how did you install it and what OS are you using?

**Comment by ghost** [comment]
@JFreegman what do you mean by latest version? That happened at release 0.8.2 at OpenBSD (note that I'm using DragonFlyBSD now). That bug only happened few times, it's hard to catch.

**Comment by JFreegman** [comment]
Closing due to inactivity
